#!usr/bin/python3.8
#coding=utf-8


#Auteur: Faxel
#Contact: t.me/Faxelh
# Le credit pour ce code va a Mr Faxel
# Si vous voulez prendre Le credit pour ce code Voyez Faster Axel.



import os,sys,time,datetime,random,hashlib,re,threading,json

from time import sleep   





# -Automatisation-#
def Street(z):
    for e in z + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(0.09)





try:

	from requests import get, post
	import json, os, subprocess as sp, sys

except Exception as ff:

	exit("\033[1;91m[\033[1;97mErreur provenance des Modules\033[1;91m]\033[1;93m %s"%(ff))

if sys.version[0] in '2':

   exit("\033[1;91m[\033[1;97mDesole\033[1;91m] \033[1;97mVous ne pouvez pas utiliser\033[1;95m python2\033[1;97m.\nVeuillez installer \033[1;96mpython3")

os.system('clear')


print ("[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●"  )           
print ("[38;5;214m•_  _ ____ \033[1;97m _  _ ____ ____ _  _\033[1;32m ____ ____   _  _• ")
print ("[38;5;214m•|\/| |__/ \033[1;97m |__| |__| |    |_/ \033[1;32m |___ |__/   |_/ • ")
print ("[38;5;214m•|  | |  \ \033[1;97m |  | |  | |___ | \_\033[1;32m |___ |  \ __| \_• "   )
print ("[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●")
print("\033[1;97m╔═════════════════════════════════════════════╗")
print("\033[1;97m║\033[1;91m[\033[1;93m**\033[1;91m]\033[38;5;95m      Developpeur \033[1;97m:\033[38;5;214m  Faxel           \033[1;91m[\033[1;93m**\033[1;91m]\033[1;97m║")
print("\033[1;97m╚═════════════════════════════════════════════╝")
print("")

try:

	Nom=input("\033[1;91m[\033[1;93m&\033[1;91m] \033[1;97mEntrer le nom d\'utilisateur github \033[1;91m: \033[1;96m")
	if Nom == '': 
		exit("\033[1;91m[\033[1;93m?\033[1;91m] \033[1;97mA plus man.")
	print("")
	re=get('https://api.github.com/users/'+Nom+'/repos')
	a=json.loads(re.text)

except Exception as ef:
	exit("\033[1;91m[\033[1;93m!\033[1;91m]\033[1;94m Erreur %s"%(ef))

items = []
try:
	for item in a:

	    items.append(item['name'])

except TypeError: exit("\033[1;91m[\033[1;93mx\033[1;91m]\033[1;97m Le nom d\'utilisateur\033[1;91m",Nom,"\033[1;97m n\'existe pas.")

s=len(items)

if s <= 0:

	#exit("\033[1;91m \033[1;96m ")
        print("\033[1;91m[\033[1;97m!\033[1;91m]\033[1;97m Le nom d\'utilisateur\033[38;5;145m",Nom,"\033[1;97m n\'a pas de referentiel.")
        exit()

elif s > 0:
                   
        print("\033[1;91m[\033[1;93m*\033[1;91m] \033[1;97mIl y\'a\033[1;91m",s,"\033[1;97mréférentiels sur le github de\033[1;96m",Nom,"\033[1;91m[\033[1;93m*\033[1;91m]\n")
        print("\033[1;96m  __ ___ ___    _     _        _ ")
        print("\033[1;96m /__  |   |    /  |  / \ |\ | |_ ")
        print("\033[1;96m \_| _|_  |    \_ |_ \_/ | \| |_\n")

c=int(1)
while c < s:
	for i in range(s):
                
                
                time.sleep(1)
                print ("\t\033[1;91m[\033[1;93m"+str(c)+"\033[1;91m]\033[1;97m Clone\033[1;92m",items[i])
                c+=1

try:

	Dmd=int(input("\n\033[1;91m[\033[1;93m*\033[1;91m] \033[1;97mClonage du lien git\033[1;91m (\033[1;95mnuméro\033[1;91m) :\033[1;96m "))
        
	if Dmd <= 0:

		exit("\033[1;91m[\033[1;93m?\033[1;91m] \033[1;97mA plus\n")
  
	os.system('git clone https://github.com/'+Nom+'/'+items[Dmd-1])

	sp.call('mv '+str(items[Dmd-1])+' ..',shell=True,stdout=sp.DEVNULL, stderr=sp.STDOUT)

	print("\n\033[1;91m[\033[1;93m@\033[1;91m]\033[1;92m Installation de \033[1;96m",items[Dmd-1],"\033[1;92mreussie\033[1;92m.")

	Street("\n\033[1;91m[\033[1;93m#\033[1;91m]\033[1;97m Verifier l\'emplacement du dossier en tapant \033[1;95m cd\033[1;97m. \033[1;91m[\033[1;93m#\033[1;91m]\n\033[1;95m\033[1;91m[\033[1;93m#\033[1;91m] cd\033[1;97m pour quitter le dossier courant.              \033[1;91m[\033[1;93m#\033[1;91m]\n\033[1;91m[\033[1;93m#\033[1;91m]\033[1;97m Ensuite taper\033[1;95m cd\033[1;91m +\033[1;97m le dossier.Puis taper\033[1;93m ls\033[1;97m.     \033[1;91m[\033[1;93m#\033[1;91m]\n ")


except KeyboardInterrupt: exit("\033[1;91m[\033[1;93m*\033[1;91m] Interruption\033[1;91m] : \033[1;94m]Arret")  
        
except Exception as F: exit("\033[1;91m[\033[1;97mA plus\033[1;91m] %s"%(F))

print("\033[1;97m╔═════════════════════════════════════════════╗")
print("\033[1;97m║\033[1;91m[\033[1;93m**\033[1;91m]\033[38;5;95m      Developpeur \033[1;97m:\033[38;5;214m  Faxel           \033[1;91m[\033[1;93m**\033[1;91m]\033[1;97m║")
print("\033[1;97m╚═════════════════════════════════════════════╝")
Street("\n             \033[1;91m[\033[1;93m**\033[1;91m] \033[38;5;214mFaxel\033[1;97m un jour,\033[38;5;214mFaxel \033[1;97mtoujours \033[1;91m[\033[1;93m**\033[1;91m] \n")
 
