#!usr/bin/python3.7
#coding=utf-8
#Auteur: Faxel
#Contact: t.me/Faxelh



# Le credit pour ce code va a Mr Faxel
# Si vous voulez prendre Le credit pour ce code Voyez Faster Axel.



import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize,fileinput
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser
from time import sleep   
from urllib2 import *
from platform import system





# -Automatisation-#
def Street(z):
    for e in z + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(0.09)





try:
	from requests import get, post
	import json, os, subprocess as sp, sys

except Exception as ff:

	exit("[Erreur provenance Module] %s"%(ff))

if sys.version[0] in '2':
   exit("[Desole] Vous utilisez python2, veuillez installer python3")

os.system('clear')


print ("[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●"  )           
print ("[238;5;214m•_  _ ____ \033[1;97m _  _ ____ ____ _  _\033[1;32m ____ ____   _  _• ")
print ("[38;5;214m•|\/| |__/ \033[1;97m |__| |__| |    |_/ \033[1;32m |___ |__/   |_/ • ")
print ("[38;5;214m•|  | |  \ \033[1;97m |  | |  | |___ | \_\033[1;32m |___ |  \ __| \_• "   )
print ("[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●")
print("\033[1;97m╔════════════════════════════════════════╗")
print("\033[1;97m║\033[1;91m[\033[1;93m**\033[1;91m]\033[38;5;95m      Developpeur \033[1;97m:\033[38;5;214m  Faxel           \033[1;91m[\033[1;93m**\033[1;91m]\033[1;97m║")
print("\033[1;97m╚═════════════════════════════════════════════╝")
print("")

try:
	u=input("\033[1;91m[\033[1;93m&\033[1;91m] \033[1;97mEntrer le nom d\'utilisateur github \033[1;91m: \033[1;96m")
	if u == '':
		exit("\033[1;91m[\033[1;93m?\033[1;91m] \033[1;97mA plus man")
	print()
	re=get('https://api.github.com/users/'+u+'/repos')
	a=json.loads(re.text)
except Exception as ef:
	exit("\033[1;91m[\033[1;93m!\033[1;91m]\033[1;97m Erreur %s"%(ef))

items = []
try:
	for item in a:
	    items.append(item['name'])
except TypeError: exit("\033[1;91m[\033[1;93mx\033[1;91m]\033[1;97m Le nom d\'utilisateur\033[1;91m ",u,"\033[1;97m n\'existe pas ")

s=len(items)
if s <= 0:
	exit("\033[1;91m\033[1;97m[Depot introuvable\033[1;91m]\033[1;97m Le nom d\'utilisateur \033[1;96m",u,"\033[1;97m n\'a pas de referentiels")
elif s > 0:
	print("\033[1;91m[\033[1;93m*\033[1;91m] \033[1;97mJ\'ai trouver \033[1;91m",s,"\033[1;97m referentiel sur le github de\033[1;96m ",u," ")

c=int(1)
while c < s:
	for i in range(s):
		print("\t["\033[1;93m+str(c)+\033[1;91m"]\033[1;97m Cloner\033[1;92m ",items[i])
		c+=1
try:
	Dmd=int(input("\n\033[1;91m[\033[1;93m*\033[1;91m] \033[1;97mClonage du lien git\033[1;91m (\033[1;95mnumero\033[1;91m) :\033[1;96m "))
	if Dmd <= 0:
		exit("\033[1;91m[\033[1;93m?\033[1;91m] \033[1;97mA plus")
	os.system('git clone https://github.com/'+u+'/'+items[Dmd-1])
	sp.call('mv '+str(items[Dmd-1])+' ..',shell=True,stdout=sp.DEVNULL, stderr=sp.STDOUT)
	print("\033[1;91m[\033[1;93m@\033[1;91m]\033[1;92m Installation reussie ",items[Dmd-1])
	print("\033[1;91m[\033[1;93m#\033[1;91m]\033[1;97m Verifier installer le dossier en tapant\033[1;95m 'cd' \033[1;97mpuis \033[1;93m'ls' ")
except KeyboardInterrupt: exit("[!] key interrupt: exit")
except Exception as F: exit("\033[1;91m[\033[1;97mA plus\033[1;91m] %s"%(F))
